"""tasks table

Revision ID: 3df0ec885db0
Revises: 13971b91adea
Create Date: 2022-12-26 18:42:17.687880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df0ec885db0'
down_revision = '13971b91adea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('contractor', sa.Integer(), nullable=True),
    sa.Column('timestamp_created', sa.DateTime(), nullable=True),
    sa.Column('timestamp_finished', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contractor'], ['user.id'], ),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_timestamp_created'), ['timestamp_created'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_timestamp_finished'), ['timestamp_finished'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_timestamp_finished'))
        batch_op.drop_index(batch_op.f('ix_task_timestamp_created'))

    op.drop_table('task')
    # ### end Alembic commands ###
