"""added comments table

Revision ID: 45e579c07742
Revises: 10a6c19e5911
Create Date: 2023-02-19 13:12:21.540845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e579c07742'
down_revision = '10a6c19e5911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_created', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_comment_timestamp_created'), ['timestamp_created'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_timestamp_created'))
        batch_op.drop_column('timestamp_created')

    # ### end Alembic commands ###
